export const ROUTE_NAMES = {
  ALARM_SETTING: 'AlarmSetting',
  ANNOUNCEMENT: 'Announcement',
  EXTERNAL_LINK: 'ExternalLink',
  HOME: 'Home',
  INFO_AGREEMENT_SETTING: 'InfoAgreementSetting',
  INQUIRY: 'Inquiry',
  LOGIN: 'Login',
  LOGIN_INFO: 'LoginInfo',
  LOGIN_WEBVIEW: 'LoginWebView',
  MAIN: 'Main',
  MY_INFO: 'MyInfo',
  MYPAGE: 'Mypage',
  PRIVACY_POLICY: 'PrivacyPolicy',
  REGISTER: 'Register',
  SCRAP: 'Scrap',
  SELECT_MAJOR: 'SelectMajor',
  SELECT_REGION: 'SelectRegion',
  SETTING: 'Setting',
  TERM_OF_USE: 'TermOfUse',
  UNIV_INFO: 'UnivInfo',
  USER_INFO: 'UserInfo',
} as const
